'use client' 

import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { Toaster } from "react-hot-toast";
import { Providers } from "./providers";
import { Header } from "./component/Header";
import Footer from "./component/Footer";
import { usePathname } from "next/navigation"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname(); 
  const isCartPage = pathname === '/cart'; 
  const isProductDetailPage = pathname.includes('/features/product/');
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <title>E-Market Place</title>
        <link rel="icon" href="/Bag-logo.png" />
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" />
      </head>
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <Providers>
          <Header />
          {children}
          <Toaster />
         
          {!isCartPage && !isProductDetailPage &&  <Footer />}
        </Providers>
      </body>
    </html>    
  );
}